### ISSUE TITLE
Create a NuGet Package

### ISSUE THREAD

**Issue by theouteredge** [JeffGos/urbanairsharp#2]
Hi,

Just found your library and it looks really good. But I would recommend creating and publish and NuGet package for this so it easier for people to consume in their application.

I look on NuGet and there are currently no Urbanairship packages, so you have the opportunity to be the first one and make a lot of people lives easier :)

**Comment by JeffGos** [comment]
Hi there

Thanks for the tip - I have been planning to do it - will get round to it soon ;)

**Comment by JeffGos** [comment]
Done :D
