### ISSUE TITLE
JsonReaderException was unhandled by the code

### ISSUE THREAD

**Issue by stefanbg** [JeffGos/urbanairsharp#5]
In Program.cs I have this code: 
var client = new UrbanAirSharpGateway(AppKey, AppMasterSecret); // Yes these are set
client.AddTagToDevices(new List<String> { BGsDeviceId }, "MyTestTag"); // BGsDeviceId is a string set to my iPhones Id. 

In UrbanAirSharpGateway.cs, the method AddTagToDevices()
return response.Result; <- This row gives an error that says:
JsonReaderException was unhandled by the code
An exception of type 'System.AggregateException' occurred in mscorlib.dll but was not handled in user code

When I debugg the variable response is: 
'response = Id = 1, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"'

A bug?

**Comment by JeffGos** [comment]
This was a because the Urban Airship service was returning invalid JSON in the response. The response sent is "OK", which cannot be parsed to a valid object by the JsonReader.

This is now handled correctly
